# Copyright The Cloud Custodian Authors.
# SPDX-License-Identifier: Apache-2.0
import json
from collections import defaultdict
from pathlib import Path

from google.api_core.client_options import ClientOptions

from c7n.manager import SyntheticResourceMixin
from c7n.utils import local_session, jmespath_search, type_schema
from c7n_gcp.actions import MethodAction
from c7n_gcp.provider import resources
from c7n_gcp.query import QueryResourceManager, TypeInfo, ChildResourceManager, ChildTypeInfo


REGION_DATA_PATH = Path(__file__).parent.parent / 'regions.json'
VERTEXAI_REGION_DATA_PATH = Path(__file__).parent.parent / 'vertexai_regions.json'
VERTEXAI_PUBLISHER_DATA_PATH = Path(__file__).parent.parent / 'vertexai_publishers.json'


@resources.register('vertex-ai-location')
class VertexAILocation(SyntheticResourceMixin):
    """Vertex AI Location pseudo-resource for multi-location enumeration.

    This is used internally by VertexAIEndpoint to support querying multiple locations.
    Loads available Vertex AI regions from vertexai_regions.json.
    """

    class resource_type(TypeInfo):
        name = id = 'name'
        scope = 'global'
        default_report_fields = ['name']
        service = 'vertex-ai-locations'

    filter_registry = {}
    action_registry = {}

    def __init__(self, ctx=None, data=()):
        self.ctx = ctx
        self.config = ctx.options if ctx else None
        self.data = data

        # Load Vertex AI supported regions from vertexai_regions.json
        # Generated by tools/dev/data_vertexai_locations.py
        with open(VERTEXAI_REGION_DATA_PATH) as fh:
            self.regions = json.load(fh)

    def get_synthetic_resources(self, query=None):
        """Return list of Vertex AI locations to query.

        Locations can be specified via:
        1. Policy query: {'query': [{'location': 'us-central1'}, {'location': 'us-east1'}]}
        2. Config regions: --regions us-central1,us-east1
        3. Config region: --region us-central1
        4. Default: All Vertex AI supported regions from vertexai_regions.json
        """

        # If query specified in policy, use those locations
        if 'query' in self.data:
            query_locations = {q['location'] for q in self.data['query'] if 'location' in q}
            return [{'name': loc} for loc in self.regions if loc in query_locations]

        # If config regions specified, use those
        if self.config and self.config.regions and 'all' not in self.config.regions:
            return [{'name': r} for r in self.regions if r in self.config.regions]

        # If single config region specified, use that
        if self.config and self.config.region and self.config.region != 'us-east-1':
            return [{'name': self.config.region}] if self.config.region in self.regions else []

        # Default: return all Vertex AI supported regions
        return [{'name': loc} for loc in self.regions]


@resources.register('vertex-ai-endpoint')
class VertexAIEndpoint(QueryResourceManager):
    """GCP Vertex AI Endpoint Resource

    Vertex AI Endpoints are used to deploy machine learning models for online prediction.

    :example:

    List all Vertex AI Endpoints in specific locations:

    .. code-block:: yaml

        policies:
          - name: vertexai-endpoints-missing-env-label
            resource: gcp.vertex-ai-endpoint
            query:
              - location: us-central1
              - location: us-east1
            filters:
              - type: value
                key: labels.env
                op: absent

    :example:

    List all Vertex AI Endpoints across all locations:

    .. code-block:: yaml

        policies:
          - name: vertexai-endpoints-all-locations
            resource: gcp.vertex-ai-endpoint
    """

    class resource_type(TypeInfo):
        service = 'aiplatform'
        version = 'v1'
        component = 'projects.locations.endpoints'
        enum_spec = ('list', 'endpoints[]', None)
        scope = 'project'
        scope_key = 'parent'
        scope_template = None  # Handled dynamically per location
        name = id = 'name'
        default_report_fields = [
            'name', 'displayName', 'deployedModels[].displayName', 'createTime', 'updateTime'
        ]
        asset_type = 'aiplatform.googleapis.com/Endpoint'
        permissions = ('aiplatform.endpoints.list',)
        urn_component = 'endpoint'
        urn_id_segments = (-1,)

        @staticmethod
        def get(client, resource_info):
            # Resource name format: projects/{project}/locations/{location}/endpoints/{endpoint}
            return client.execute_query(
                'get', {'name': resource_info['resourceName']})

        @classmethod
        def _get_location(cls, resource):
            """Extract location from resource name."""
            # Resource name format: projects/{project}/locations/{location}/endpoints/{endpoint}
            return resource['name'].split('/')[3]

    def _fetch_resources(self, query):
        """Override to handle location-specific API endpoints and multi-location enumeration.

        Vertex AI requires:
        1. Location-specific hostnames (e.g., us-central1-aiplatform.googleapis.com)
        2. Location in the parent scope (e.g., projects/{project}/locations/{location})
        3. Enumeration across multiple locations (similar to RegionalResourceManager)
        """

        session = local_session(self.session_factory)
        project = session.get_default_project()

        # Get locations to query
        location_query = self._get_location_query()
        location_manager = self.get_resource_manager(
            resource_type='vertex-ai-location',
            data=({'query': location_query} if location_query else {})
        )

        all_resources = []
        annotation_key = 'c7n:location'

        # Enumerate resources in each location
        for location_instance in location_manager.resources():
            location = location_instance['name']

            # Build location-specific API endpoint (must include https:// scheme)
            api_endpoint = f'https://{location}-aiplatform.googleapis.com'
            client_options = ClientOptions(api_endpoint=api_endpoint)

            # Get client with location-specific endpoint
            client = session.client(
                self.resource_type.service,
                self.resource_type.version,
                self.resource_type.component,
                client_options=client_options
            )

            # Build the parent scope with project and location
            parent = f'projects/{project}/locations/{location}'

            # Execute the list operation for this location
            enum_op, path, _ = self.resource_type.enum_spec
            params = {'parent': parent}

            # Invoke the client enumeration (Vertex AI API supports pagination)
            location_resources = []
            for page in client.execute_paged_query(enum_op, params):
                page_items = jmespath_search(path, page)
                if page_items:
                    location_resources.extend(page_items)

            # Annotate resources with their location
            for resource in location_resources:
                resource[annotation_key] = location_instance

            all_resources.extend(location_resources)

        return all_resources

    def _get_location_query(self):
        """Get location query for multi-location enumeration.

        Returns query to pass to vertex-ai-location resource manager.
        If policy has 'query' specified, use that to filter locations.
        Otherwise, return None to use default location logic.

        Returns:
            list or None: Location query list or None for defaults
        """
        # If policy has query specified, pass it through to location manager
        if 'query' in self.data:
            return self.data['query']

        # Otherwise, let location manager use config.regions or config.region
        return None


@VertexAIEndpoint.action_registry.register('delete')
class VertexAIEndpointDelete(MethodAction):
    """Delete Vertex AI Endpoints

    Deletes a Vertex AI Endpoint. Note that this is an asynchronous operation
    that returns a long-running operation. The endpoint will be deleted in the background.

    **Warning**: Deleting an endpoint will undeploy all models from the endpoint.
    Make sure to check for deployed models before deletion if needed.

    :example:

    Delete endpoints with no deployed models:

    .. code-block:: yaml

        policies:
          - name: delete-unused-endpoints
            resource: gcp.vertex-ai-endpoint
            filters:
              - type: value
                key: deployedModels
                value: []
            actions:
              - type: delete

    https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.endpoints/delete
    """

    schema = type_schema('delete')
    method_spec = {'op': 'delete'}
    permissions = ('aiplatform.endpoints.delete',)

    def get_resource_params(self, model, resource):
        return {'name': resource['name']}

    def process(self, resources):
        """Process resources by grouping them by location.

        Override to group resources by location and create one client per location
        """
        # Group resources by location
        resources_by_location = defaultdict(list)

        for resource in resources:
            # Extract location from resource name
            # Format: projects/{project}/locations/{location}/endpoints/{endpoint}
            location = resource['name'].split('/')[3]
            resources_by_location[location].append(resource)

        # Process each location's resources with a location-specific client
        session = local_session(self.manager.session_factory)
        model = self.manager.resource_type

        for location, location_resources in resources_by_location.items():
            # Create location-specific client
            api_endpoint = f'https://{location}-aiplatform.googleapis.com'
            client_options = ClientOptions(api_endpoint=api_endpoint)
            location_client = session.client(
                model.service, model.version, model.component,
                client_options=client_options
            )

            # Use parent's process_resource_set with location-specific client
            self.process_resource_set(location_client, model, location_resources)


@resources.register('vertex-ai-batch-prediction-job')
class VertexAIBatchPredictionJob(QueryResourceManager):
    """GCP Vertex AI Batch Prediction Job Resource

    Vertex AI Batch Prediction Jobs are used to run batch inference workloads
    on machine learning models at scale.

    :example:

    List all Batch Prediction Jobs in specific locations:

    .. code-block:: yaml

        policies:
          - name: vertexai-batch-jobs-inventory
            resource: gcp.vertex-ai-batch-prediction-job
            query:
              - location: us-central1
              - location: us-east1

    :example:

    Find long-running batch prediction jobs:

    .. code-block:: yaml

        policies:
          - name: vertexai-batch-jobs-long-running
            resource: gcp.vertex-ai-batch-prediction-job
            filters:
              - type: value
                key: state
                value: JOB_STATE_RUNNING
              - type: value
                key: createTime
                value_type: age
                op: greater-than
                value: 24

    :example:

    Find failed batch prediction jobs:

    .. code-block:: yaml

        policies:
          - name: vertexai-batch-jobs-failed
            resource: gcp.vertex-ai-batch-prediction-job
            filters:
              - type: value
                key: state
                value: JOB_STATE_FAILED
    """

    class resource_type(TypeInfo):
        service = 'aiplatform'
        version = 'v1'
        component = 'projects.locations.batchPredictionJobs'
        enum_spec = ('list', 'batchPredictionJobs[]', None)
        scope = 'project'
        scope_key = 'parent'
        scope_template = None  # Handled dynamically per location
        name = id = 'name'
        default_report_fields = [
            'name', 'displayName', 'state', 'createTime', 'updateTime'
        ]
        asset_type = 'aiplatform.googleapis.com/BatchPredictionJob'
        permissions = ('aiplatform.batchPredictionJobs.list',)
        urn_component = 'batch-prediction-job'
        urn_id_segments = (-1,)

        @staticmethod
        def get(client, resource_info):
            # Resource name format:
            # projects/{project}/locations/{location}/batchPredictionJobs/{job}
            return client.execute_query(
                'get', {'name': resource_info['resourceName']})

        @classmethod
        def _get_location(cls, resource):
            """Extract location from resource name."""
            # Resource name format:
            # projects/{project}/locations/{location}/batchPredictionJobs/{job}
            return resource['name'].split('/')[3]

    def _fetch_resources(self, query):
        """Override to handle location-specific API endpoints and multi-location enumeration.

        Vertex AI requires:
        1. Location-specific hostnames (e.g., us-central1-aiplatform.googleapis.com)
        2. Location in the parent scope (e.g., projects/{project}/locations/{location})
        3. Enumeration across multiple locations (similar to RegionalResourceManager)
        """

        session = local_session(self.session_factory)
        project = session.get_default_project()

        # Get locations to query
        location_query = self._get_location_query()
        location_manager = self.get_resource_manager(
            resource_type='vertex-ai-location',
            data=({'query': location_query} if location_query else {})
        )

        all_resources = []
        annotation_key = 'c7n:location'

        # Enumerate resources in each location
        for location_instance in location_manager.resources():
            location = location_instance['name']

            # Build location-specific API endpoint (must include https:// scheme)
            api_endpoint = f'https://{location}-aiplatform.googleapis.com'
            client_options = ClientOptions(api_endpoint=api_endpoint)

            # Get client with location-specific endpoint
            client = session.client(
                self.resource_type.service,
                self.resource_type.version,
                self.resource_type.component,
                client_options=client_options
            )

            # Build the parent scope with project and location
            parent = f'projects/{project}/locations/{location}'

            # Execute the list operation for this location
            enum_op, path, _ = self.resource_type.enum_spec
            params = {'parent': parent}

            # Invoke the client enumeration (Vertex AI API supports pagination)
            location_resources = []
            for page in client.execute_paged_query(enum_op, params):
                page_items = jmespath_search(path, page)
                if page_items:
                    location_resources.extend(page_items)

            # Annotate resources with their location
            for resource in location_resources:
                resource[annotation_key] = location_instance

            all_resources.extend(location_resources)

        return all_resources

    def _get_location_query(self):
        """Get location query for multi-location enumeration.

        Returns query to pass to vertex-ai-location resource manager.
        If policy has 'query' specified, use that to filter locations.
        Otherwise, return None to use default location logic.

        Returns:
            list or None: Location query list or None for defaults
        """
        # If policy has query specified, pass it through to location manager
        if 'query' in self.data:
            return self.data['query']

        # Otherwise, let location manager use config.regions or config.region
        return None


@VertexAIBatchPredictionJob.action_registry.register('delete')
class VertexAIBatchPredictionJobDelete(MethodAction):
    """Delete Vertex AI Batch Prediction Jobs

    Deletes a Vertex AI Batch Prediction Job. Note that this is an asynchronous operation
    that returns a long-running operation. The job will be deleted in the background.

    **Warning**: This permanently deletes the batch prediction job and its metadata.
    Job results in Cloud Storage are not affected.

    :example:

    Delete failed batch prediction jobs:

    .. code-block:: yaml

        policies:
          - name: delete-failed-batch-jobs
            resource: gcp.vertex-ai-batch-prediction-job
            filters:
              - type: value
                key: state
                value: JOB_STATE_FAILED
            actions:
              - type: delete

    https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.batchPredictionJobs/delete
    """

    schema = type_schema('delete')
    method_spec = {'op': 'delete'}
    permissions = ('aiplatform.batchPredictionJobs.delete',)

    def get_resource_params(self, model, resource):
        return {'name': resource['name']}

    def process(self, resources):
        """Process resources by grouping them by location.

        Override to group resources by location and create one client per location
        """
        # Group resources by location
        resources_by_location = defaultdict(list)

        for resource in resources:
            # Extract location from resource name
            # Format: projects/{project}/locations/{location}/batchPredictionJobs/{job}
            location = resource['name'].split('/')[3]
            resources_by_location[location].append(resource)

        # Process each location's resources with a location-specific client
        session = local_session(self.manager.session_factory)
        model = self.manager.resource_type

        for location, location_resources in resources_by_location.items():
            # Create location-specific client
            api_endpoint = f'https://{location}-aiplatform.googleapis.com'
            client_options = ClientOptions(api_endpoint=api_endpoint)
            location_client = session.client(
                model.service, model.version, model.component,
                client_options=client_options
            )

            # Use parent's process_resource_set with location-specific client
            self.process_resource_set(location_client, model, location_resources)


@VertexAIBatchPredictionJob.action_registry.register('stop')
class VertexAIBatchPredictionJobStop(MethodAction):
    """Stop (Cancel) Vertex AI Batch Prediction Jobs

    Cancels a running Vertex AI Batch Prediction Job. This is useful for cost control
    and incident response when jobs are running longer than expected or consuming
    unexpected resources.

    **Note**: Only jobs in JOB_STATE_RUNNING or JOB_STATE_PENDING can be cancelled.
    Completed, failed, or already cancelled jobs cannot be cancelled.

    :example:

    Cancel long-running batch prediction jobs:

    .. code-block:: yaml

        policies:
          - name: cancel-long-running-batch-jobs
            resource: gcp.vertex-ai-batch-prediction-job
            filters:
              - type: value
                key: state
                value: JOB_STATE_RUNNING
              - type: value
                key: createTime
                value_type: age
                op: greater-than
                value: 24
            actions:
              - type: stop

    :example:

    Cancel all running batch jobs (emergency cost control):

    .. code-block:: yaml

        policies:
          - name: emergency-cancel-all-batch-jobs
            resource: gcp.vertex-ai-batch-prediction-job
            filters:
              - type: value
                key: state
                value: JOB_STATE_RUNNING
            actions:
              - type: stop

    https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.batchPredictionJobs/cancel
    """

    schema = type_schema('stop')
    method_spec = {'op': 'cancel'}
    permissions = ('aiplatform.batchPredictionJobs.cancel',)

    def get_resource_params(self, model, resource):
        return {'name': resource['name']}

    def process(self, resources):
        """Process resources by grouping them by location.

        Override to group resources by location and create one client per location.
        """
        # Group resources by location
        resources_by_location = defaultdict(list)

        for resource in resources:
            # Extract location from resource name
            # Format: projects/{project}/locations/{location}/batchPredictionJobs/{job}
            location = resource['name'].split('/')[3]
            resources_by_location[location].append(resource)

        # Process each location's resources with a location-specific client
        session = local_session(self.manager.session_factory)
        model = self.manager.resource_type

        for location, location_resources in resources_by_location.items():
            # Create location-specific client
            api_endpoint = f'https://{location}-aiplatform.googleapis.com'
            client_options = ClientOptions(api_endpoint=api_endpoint)
            location_client = session.client(
                model.service, model.version, model.component,
                client_options=client_options
            )

            # Use parent's process_resource_set with location-specific client
            self.process_resource_set(location_client, model, location_resources)


def get_vertex_ai_publishers():
    """Load Vertex AI Model Garden publishers from generated JSON data."""
    with open(VERTEXAI_PUBLISHER_DATA_PATH) as fh:
        publishers = json.load(fh)

    return publishers


@resources.register('vertex-ai-publisher')
class VertexAIPublisher(SyntheticResourceMixin, QueryResourceManager):
    """GCP Resource for Vertex AI Model Garden Publishers

    This resource provides a list of publishers in Vertex AI Model Garden.
    It serves as a parent resource for vertex-ai-publisher-model.

    Note: This is a synthetic resource based on generated publisher data,
    loaded from vertexai_publishers.json.

    :example: List all Vertex AI publishers

    .. code-block:: yaml

        policies:
          - name: vertex-ai-publishers
            resource: gcp.vertex-ai-publisher
    """

    class resource_type(TypeInfo):
        service = 'aiplatform'
        version = 'v1beta1'
        component = 'publishers'
        scope = 'global'
        name = id = 'name'
        default_report_fields = ['name']
        permissions = ()  # No specific permissions needed for synthetic resource
        urn_component = 'publisher'

    def get_synthetic_resources(self, query=None):
        """Return synthetic publisher resources."""
        return [{'name': f'publishers/{publisher}'} for publisher in get_vertex_ai_publishers()]


@resources.register('vertex-ai-publisher-model')
class VertexAIPublisherModel(ChildResourceManager):
    """GCP Resource for Vertex AI Model Garden Publisher Models

    https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/publishers.models

    This resource provides access to the Vertex AI Model Garden catalog of
    publisher models from all configured publishers (Google, Anthropic, Meta, etc.).

    Note: Uses v1beta1 API because v1 does not support list operations.
    As of 2026-03, the v1 API only has 'get' method for publishers.models.
    When v1 adds list support, migrate to v1 (expect 180-day deprecation notice
    per Google Cloud's beta API policy: https://google.aip.dev/185).

    :example: List all Vertex AI publisher models from all publishers

    .. code-block:: yaml

        policies:
          - name: vertex-ai-publisher-models
            resource: gcp.vertex-ai-publisher-model

    :example: List only Anthropic models

    .. code-block:: yaml

        policies:
          - name: anthropic-models
            resource: gcp.vertex-ai-publisher-model
            filters:
              - type: value
                key: name
                op: regex
                value: 'publishers/anthropic/.*'
    """

    def get_permissions(self):
        """Override to return empty permissions - catalog is publicly readable."""
        return ()

    def _get_child_enum_args(self, parent_instance):
        """Extract parent parameter for listing models."""
        return {'parent': parent_instance['name']}

    class resource_type(ChildTypeInfo):
        service = 'aiplatform'
        # TODO: Migrate to v1 when list support is added
        version = 'v1beta1'
        # version = 'v1'  # Uncomment when v1 supports list operations

        component = 'publishers.models'
        enum_spec = ('list', 'publisherModels[]', None)
        scope = 'global'
        name = id = 'name'
        default_report_fields = [
            'name', 'versionId', 'publisherModelTemplate', 'launchStage']
        # No specific permissions - publisher models catalog is publicly readable
        permissions = ()
        urn_component = 'publisher-model'
        urn_id_segments = (-1,)
        parent_spec = {'resource': 'vertex-ai-publisher'}
